version: '3.8'

services:
  app:
    image: ghcr.io/calmar-game/backend:latest
    container_name: game_app
    restart: always
    env_file:
      - ${PWD}/environment/${ENV_NAME}/.env.${ENV_NAME}.dist
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_SCHEMA: ${POSTGRES_SCHEMA}
      JWT_SECRET: ${JWT_SECRET}
    expose:
      - "8000"
    depends_on:
      - postgres
    networks:
      - calmar_network

  frontend:
    image: ghcr.io/calmar-game/frontend:latest
    container_name: calmar_game_frontend
    restart: always
    expose:
      - "80"
    networks:
      - calmar_network

  postgres:
    image: postgres:14
    container_name: calmar_game_postgres
    restart: always
    env_file:
      - ${PWD}/environment/${ENV_NAME}/.env.${ENV_NAME}.dist
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-game_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - calmar_network

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: always
    expose:
      - "8080"
    depends_on:
      - postgres
    networks:
      - calmar_network

  caddy:
    image: caddy:2
    container_name: calmar_game_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - /var/www/backendforgames.com:/var/www/backendforgames.com:ro
    networks:
      - calmar_network

volumes:
  pgdata:
    driver: local
    name: "${ENV_NAME}_pgdata"

  caddy_data:
  caddy_config:

networks:
  calmar_network: